services:
  db:
    image: postgres:16-alpine
    container_name: awos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - awos_db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  web:
    build:
      context: ./evaluacion-c1
      dockerfile: Dockerfile
    container_name: awos_web
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:${WEB_PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./evaluacion-c1:/app
      - /app/node_modules

volumes:
  awos_db_data: